# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-27 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=8)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('business_phone', models.CharField(max_length=32)),
                ('mobile', models.CharField(max_length=32)),
                ('location', models.CharField(max_length=32)),
                ('comment', models.TextField()),
                ('notes', models.TextField()),
                ('may_contact', models.BooleanField()),
                ('launch_meeting', models.BooleanField()),
                ('after_meeting', models.BooleanField()),
                ('access', models.BooleanField()),
                ('report_access', models.BooleanField()),
                ('invoice', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('code', models.CharField(max_length=32)),
                ('engagement_specialist', models.EmailField(max_length=254)),
                ('super_sector', models.CharField(max_length=32)),
                ('grading', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=32)),
                ('general_comments', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='companies.Client')),
            ],
        ),
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('subsector', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='SuperSector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supersector', to='companies.Sector')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='YearOfParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('active', models.BooleanField()),
                ('client_contacts', models.ManyToManyField(to='companies.ClientContact')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='years', to='companies.Company')),
                ('contract_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='years', to='companies.ContractType')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='years', to='companies.Survey')),
            ],
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='companies.Company'),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='surveys',
            field=models.ManyToManyField(related_name='clients', to='companies.Survey'),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='trainings',
            field=models.ManyToManyField(related_name='contacts', to='companies.Training'),
        ),
    ]
