# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-03 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=8)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('business_phone', models.CharField(max_length=32)),
                ('mobile', models.CharField(max_length=32)),
                ('location', models.CharField(max_length=32)),
                ('comment', models.TextField()),
                ('notes', models.TextField()),
                ('may_contact', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=32)),
                ('grading_system', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=128)),
                ('general_comments', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='companies.Client')),
            ],
        ),
        migrations.CreateModel(
            name='CompanySetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engagement_specialist', models.EmailField(max_length=254)),
                ('contract_type', models.CharField(max_length=32)),
                ('is_active', models.BooleanField()),
                ('surveys', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ContactSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surveys', models.CharField(max_length=32)),
                ('launch_meeting', models.BooleanField()),
                ('after_meeting', models.BooleanField()),
                ('trainings', models.CharField(max_length=32)),
                ('access', models.BooleanField()),
                ('report_access', models.BooleanField()),
                ('invoice', models.BooleanField()),
                ('client_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setups', to='companies.ClientContact')),
            ],
        ),
        migrations.CreateModel(
            name='YearOfParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='years', to='companies.Company')),
                ('company_setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year', to='companies.CompanySetup')),
            ],
        ),
        migrations.AddField(
            model_name='contactsetup',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='companies.YearOfParticipation'),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='companies.Company'),
        ),
    ]
