# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-27 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yearofparticipation',
            name='survey',
        ),
        migrations.AddField(
            model_name='yearofparticipation',
            name='surveys',
            field=models.ManyToManyField(related_name='years', to='companies.Survey'),
        ),
    ]
