# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-27 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20170927_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='surveys',
            field=models.ManyToManyField(related_name='companies', to='companies.Survey'),
        ),
    ]
